language: python
python: "3.3"
node_js: "0.10"

services:
 - postgresql
 - memcached

virtualenv:
  system_site_packages: true

before_install:
 - psql -c 'create database openreview;' -U postgres
 - export DJANGO_DB_USER=postgres
 - export DJANGO_LOG_LEVEL=WARNING
 - export DJANGO_FORCE_STATICFILES=1

 # Setup virtual display for in-browser testing
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"


install:
 # Upgrading nodejs..
 - sudo apt-get install python-software-properties
 - sudo add-apt-repository ppa:chris-lea/node.js -y
 - sudo apt-get update
 - cat openreview/apt_requirements.txt | tr '\n' ' ' | xargs sudo apt-get install -y
 - sudo apt-get build-dep lxml
 - sudo apt-get install nodejs
 - sudo npm install -g bower
 - cd static; bower install; cd ..
 - pip install -r openreview/pip_requirements.txt --use-mirrors --upgrade
 - pip install coverage coveralls

script:
 - coverage run --source=openreview --omit=*/migrations/*,openreview/wsgi.py manage.py test

after_success:
 - coverage report -m
 - coveralls
