language: python
python:
  - "3.4"
  - "3.3"

services:
 - postgresql
 - memcached
 - elasticsearch

virtualenv:
  system_site_packages: false

before_install:
 - psql -c 'create database openreview;' -U postgres
 - export DJANGO_DB_USER=postgres
 - export DJANGO_LOG_LEVEL=WARNING
 - export DJANGO_FORCE_STATICFILES=1

 # Setup virtual display for in-browser testing
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"


install:
 # Installing from caches:
 - curl http://hmbastiaan.nl/martijn/open-review/lxml-$TRAVIS_PYTHON_VERSION.tar.gz | tar xzf - -C /
 - curl http://hmbastiaan.nl/martijn/open-review/psycopg2-$TRAVIS_PYTHON_VERSION.tar.gz | tar xzf - -C /
 # Upgrading nodejs..
 - sudo apt-get install python-software-properties
 - sudo add-apt-repository ppa:chris-lea/node.js -y
 - sudo apt-get update
 - sudo apt-get install nodejs
 - sudo npm install -g bower
 - bower install
 - cat openreview/requirements/apt/{common,dev,prod}.txt | tr '\n' ' ' | xargs sudo apt-get install -y
 - pip install -r openreview/requirements/pip/dev.txt --use-mirrors
 - pip install -r openreview/requirements/pip/prod.txt --use-mirrors
 #- To reset psycopg2 and lxml caches, set up a sftp server with username and password 'test':
 #- sudo apt-get install sshpass
 #- tar -zcvf lxml-$TRAVIS_PYTHON_VERSION.tar.gz /home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION.*/lib/python$TRAVIS_PYTHON_VERSION/site-packages/lxml*
 #- tar -zcvf psycopg2-$TRAVIS_PYTHON_VERSION.tar.gz /home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION.*/lib/python$TRAVIS_PYTHON_VERSION/site-packages/psycopg*
 #- sshpass -p 'test' scp -o StrictHostKeyChecking=no -P 2224 lxml-$TRAVIS_PYTHON_VERSION.tar.gz test@opdakken.hmbastiaan.nl:/home/test
 #- sshpass -p 'test' scp -o StrictHostKeyChecking=no -P 2224 psycopg2-$TRAVIS_PYTHON_VERSION.tar.gz test@opdakken.hmbastiaan.nl:/home/test

script:
 - coverage run --source=openreview --omit=*/migrations/*,openreview/wsgi.py manage.py test

after_success:
 - coverage report -m
 - coveralls

notifications:
  email: false
